# ci/build.yml

version: v2.0
name: 矩阵测试
stages:
- name: 静态矩阵
  jobs:
    node-build:
        strategy:
          matrix:
            var1: ['OFF', 'ON']
            var2: [ { a: '1', b: '2' }, { a: '3', b: '4' } ]
        steps:
          - run: echo ${{ matrix.var2.a }}
            name: node.js编译
